### ISSUE TITLE
Incoming PRs, but iris-relay no longer compiles

### ISSUE THREAD

**Issue by Fmstrat** [linkedin/iris-relay#69]
Hi,

I'm about to send in about 6-10 patches via PRs for Oncall and Iris to fix OWA sync, add pushover.net support, include SSL support in SMTP, add a Microsoft Teams compatible endpoint, include incident creation from inbound support emails, etc.

However, for the life of me I can't get `iris-relay` to compile. I've followed the `Dockerfile`, no luck. I've rebuilt on newer versions of Ubuntu, no luck. My only guess is that it only runs on a version of Python 2.x that simply isn't available anymore. The error I hit now, after manually including `pathlib` and other required updates to the commands in the Dockerfile is:

```
Traceback (most recent call last):
  File "/home/iris/setup.py", line 53, in <module>
    'iris-relay-dev = iris_relay.bin.run_server:main'
  File "/home/iris/env/local/lib/python2.7/site-packages/setuptools/__init__.py", line 162, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/iris/env/local/lib/python2.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/iris/env/local/lib/python2.7/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/home/iris/env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 424, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/iris/env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 666, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/iris/env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 713, in install_item
    self.process_distribution(spec, dist, deps)
  File "/home/iris/env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 758, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/home/iris/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 774, in resolve
    replace_conflicting=replace_conflicting
  File "/home/iris/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1057, in best_match
    return self.obtain(req, installer)
  File "/home/iris/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1069, in obtain
    return installer(requirement)
  File "/home/iris/env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 685, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/iris/env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 711, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/iris/env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 896, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/iris/env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1164, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/iris/env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1150, in run_setup
    run_setup(setup_script, args)
  File "/home/iris/env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/iris/env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/iris/env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/home/iris/env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/home/iris/env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/iris/env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/iris/env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/iris/env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-2NyUop/PyJWT-2.3.0/setup.py", line 5, in <module>
    import setuptools
  File "/home/iris/env/local/lib/python2.7/site-packages/setuptools/__init__.py", line 162, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 124, in setup
    dist.parse_config_files()
  File "/home/iris/env/local/lib/python2.7/site-packages/setuptools/dist.py", line 702, in parse_config_files
    ignore_option_errors=ignore_option_errors)
  File "/home/iris/env/local/lib/python2.7/site-packages/setuptools/config.py", line 121, in parse_configuration
    meta.parse()
  File "/home/iris/env/local/lib/python2.7/site-packages/setuptools/config.py", line 426, in parse
    section_parser_method(section_options)
  File "/home/iris/env/local/lib/python2.7/site-packages/setuptools/config.py", line 399, in parse_section
    self[name] = value
  File "/home/iris/env/local/lib/python2.7/site-packages/setuptools/config.py", line 184, in __setitem__
    value = parser(value)
  File "/home/iris/env/local/lib/python2.7/site-packages/setuptools/config.py", line 515, in _parse_version
    version = self._parse_attr(value, self.package_dir)
  File "/home/iris/env/local/lib/python2.7/site-packages/setuptools/config.py", line 350, in _parse_attr
    value = getattr(module, attr_name)
AttributeError: 'module' object has no attribute '__version__'
```

Current Dockerfile I'm testing with (same results with 16.04):
```
FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get -y install python-pip uwsgi virtualenv sudo python-dev libyaml-dev \
       libsasl2-dev libldap2-dev nginx uwsgi-plugin-python libssl-dev libffi-dev  \
    && rm -rf /var/cache/apt/archives/*

RUN useradd -m -s /bin/bash iris

ADD docker/daemons /home/iris/daemons
ADD src /home/iris/src
ADD setup.py /home/iris/setup.py
ADD README.md /home/iris
WORKDIR /home/iris

RUN chown -R iris:iris /home/iris /var/log/nginx /var/lib/nginx \
    && sudo -Hu iris mkdir -p /home/iris/var/log/uwsgi /home/iris/var/log/nginx /home/iris/var/run /home/iris/var/relay \
    && sudo -Hu iris virtualenv /home/iris/env \
    && sudo -Hu iris /bin/bash -c 'source /home/iris/env/bin/activate && pip install pathlib && python /home/iris/setup.py install'

EXPOSE 16648

# uwsgi runs nginx. see uwsgi.yaml for details
CMD ["/usr/bin/uwsgi", "--yaml", "/home/iris/daemons/uwsgi.yaml:prod"]
```

**Comment by diegocepedaw** [comment]
Hi @Fmstrat we don't use the Docker to run/develop Iris-Relay so I would have to do some more testing to tell you if this is the exact issue you are facing but when running it directly using the make file I use a Python 3.6.5 virtual env. Can you tell me if you are able to run it using Python 3.6.5?

**Comment by Fmstrat** [comment]
@diegocepedaw Thanks! I managed to get it to compile in 3.8. I'll add that to my update list for PRs.

That being said, the documentation, example repos, and Dockerfiles are way outdated. Figuring this process out has mostly been reading code to figure out how to do much of anything, or what configuration options mean. I know this is simply LinkedIn open sourcing something they use, which is fantastic and I'm 100% behind, but I'd love to see some updated documentation.

For instance, my next step is to trace through the relay config to determine what's actually required or not to complete my use case.

**Comment by Fmstrat** [comment]
Sounds good. I'm just holding off until I have a full system running, that way I know everything I'm submitting works end-to-end.

**Comment by Fmstrat** [comment]
@diegocepedaw So maybe you can help me with what I think is the last step. When accessing `iris-mobile` via browser, and logging in with one of my usernames `(`LDAP->oncall->iris`) and no password (since there is no password field), I unsurprisingly get a 401 when my browser makes a request from `iris-relay`. This 401 is accompanied by a CORS error, but I don't think that's the actual issue. I think I have a key mismatched, or need to do something to allow passwords in the mobile application. Any direction you could point me?
